### ISSUE TITLE
labelClassName 是否支持表达式？

### ISSUE THREAD

**Issue by hanchenxu** [artdong/react-org-tree#26]
![image](https://user-images.githubusercontent.com/36257490/162398758-3a173fa8-7577-4e06-bb59-fa35518acf12.png)
![image](https://user-images.githubusercontent.com/36257490/162398820-64865c9d-8147-40f7-90b3-e2d36c91e178.png)

**Comment by artdong** [comment]
目前暂不支持，你可以换一种方式来写，样式判断写在组建之外。
