### ISSUE TITLE
点击空白区域时会触发onclick，如何实现只有点击节点时才触发onclick

### ISSUE THREAD

**Issue by hanchenxu-cxhan** [artdong/react-org-tree#9]
点击空白区域时会触发onclick，
![image](https://user-images.githubusercontent.com/65534690/111931008-3bcf6400-8af5-11eb-9c36-e6cb811a5c34.png)

如何实现只有点击节点时才触发onclick

**Comment by artdong** [comment]
@hanchenxu-cxhan 按照这样添加onClick事件就可以了 https://github.com/artdong/antd-admin/blob/master/src/pages/org_tree.jsx
